name: crypto_puz
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.1
  firebase_auth: ^4.4.2
  firebase_dynamic_links: ^5.1.1
  audioplayers: ^4.0.1
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  connectivity_plus: ^3.0.6
  url_launcher: ^6.1.10
  google_mobile_ads: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter_native_splash:
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/boards/4x4/
    - assets/icons/